# Generated by Django 5.2.8 on 2025-11-06 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='filedata',
            old_name='create_at',
            new_name='created_at',
        ),
    ]
