# Generated by Django 5.2.8 on 2025-11-06 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_rename_create_at_filedata_created_at'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='filedata',
            index=models.Index(fields=['name', 'category'], name='task_fileda_name_326a55_idx'),
        ),
        migrations.AddIndex(
            model_name='filedata',
            index=models.Index(fields=['-created_at'], name='task_fileda_created_ad590c_idx'),
        ),
    ]
