# Generated by Django 5.2.8 on 2025-11-06 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0003_filedata_task_fileda_name_326a55_idx_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='filedata',
            name='task_fileda_name_326a55_idx',
        ),
        migrations.AddIndex(
            model_name='filedata',
            index=models.Index(fields=['name', 'category', 'price'], name='task_fileda_name_8a1c22_idx'),
        ),
    ]
